language: node_js

node_js:
  - "lts/*"

install:
  - npm install

jobs:
  include:
    - stage: test
      # ui tests
      cache:
        directories:
          - "ui/node_modules"
      before_install:
        - cd ui
      script:
        - npm run lint
        - npm run unit
    - # server tests
      cache:
        directories:
          - "server/node_modules"
      before_install:
        - cd server
        - cp .env.example .env
      script:
        - npm run lint
        - npm test
